import { chromium } from 'playwright'
import { installBridge } from '/home/claude/maison/e2e/cloud-bridge.mjs'
const BASE='https://cloudchaserz.frappe.cloud'
const b=await chromium.launch()
const ctx=await b.newContext({viewport:{width:1366,height:1024}})
if(process.env.BRIDGE==='1') await installBridge(ctx,{baseURL:BASE})
const p=await ctx.newPage()
const errs=[]; p.on('console',m=>{if(m.type()==='error')errs.push(m.text())})
await p.goto(BASE+'/login',{waitUntil:'domcontentloaded'})
await p.fill('#login_email','hou.mtr.a1@cloudchaserz.example')
await p.fill('#login_password','cloud123')
await Promise.all([p.waitForNavigation({timeout:45000}).catch(()=>{}), p.click('.btn-login')])
await p.waitForTimeout(3000)
console.log('after login url:', p.url())
await p.goto(BASE+'/pos',{waitUntil:'domcontentloaded'})
await p.waitForTimeout(6000)
console.log('pos url:', p.url())
const txt=(await p.locator('body').innerText()).replace(/\s+/g,' ').slice(0,300)
console.log('pos text:', txt)
await p.screenshot({path:'/tmp/login-pos.png'})
console.log('console errors:', errs.slice(0,5))
await b.close()
