import { launch, check, save, shot, BASE } from './lib-dash.mjs'
const { browser, page, console_ } = await launch()
await page.goto(`${BASE}/maison-dashboard`, { waitUntil: 'domcontentloaded' })
await page.waitForSelector('[data-testid="live-cards"] .bcard', { timeout: 45000 })
await page.waitForTimeout(2500)
// KPI close-up evidence for the card/cash + avg ticket findings
await page.locator('.kpis').screenshot({ path: '/home/claude/maison/e2e/qa/shots-dashboard/19-kpi-strip-card-negative.png' })
const kpi = await page.locator('.kpis').innerText()
check('KPI strip evidence captured', true, kpi.replace(/\n/g, ' | '))
// region filter shot
await page.locator('.list .toolbar .seg').first().locator('.btn:text-is("Tulsa Metro")').click()
await page.waitForTimeout(500)
await shot(page, '20-live-region-tulsa-1920.png')
await page.locator('.list .toolbar .seg').first().locator('.btn:text-is("All")').click()
await page.waitForTimeout(400)
// search shot
await page.fill('.list .toolbar .search', 'montrose')
await page.waitForTimeout(500)
await shot(page, '21-live-search-1920.png')
await page.fill('.list .toolbar .search', '')
await page.waitForTimeout(300)
// clients tier chips evidence
await page.goto(`${BASE}/maison-dashboard?view=clients`, { waitUntil: 'domcontentloaded' })
await page.waitForSelector('.clients .card', { timeout: 30000 })
await page.waitForTimeout(2500)
await page.locator('.clients .toolbar .btn:text-is("Collector")').click()
await page.waitForTimeout(1200)
const emptied = await page.locator('.card.churn .li[data-signal]').count()
const emptyMsg = await page.locator('.card.churn').innerText()
check('tier chip "Collector" empties the churn list on CloudChaserz', emptied === 0, `${emptied} rows; card text: "${emptyMsg.replace(/\n/g, ' | ').slice(0, 180)}"`)
await shot(page, '22-clients-tier-empty-1920.png')
await page.locator('.clients .toolbar .btn:text-is("Collector")').click()
await page.waitForTimeout(800)
// reports "FRAPPE DESK" evidence
await page.goto(`${BASE}/maison-dashboard?view=reports`, { waitUntil: 'domcontentloaded' })
await page.waitForSelector('section.reports .group', { timeout: 30000 })
await page.waitForTimeout(1500)
await page.locator('section.reports').screenshot({ path: '/home/claude/maison/e2e/qa/shots-dashboard/23-reports-frappe-desk.png' })
const rt = await page.locator('section.reports .head').innerText()
check('Reports header text captured', true, rt.replace(/\n/g, ' | '))
save('results-e9.json')
await browser.close()
